deployment:
  tasks:
    # Paths
    - export COMPOSER_BIN=/home/quickerf/composer.phar
    - export REPOPATH=/home/quickerf/laravel_suites_repo/quickerfaster.com
    - export DEPLOYPATH=/home/quickerf/laravel_app
    - export LOGDIR=/home/quickerf/deploy_logs
    - mkdir -p $LOGDIR
    - export LOGFILE=$LOGDIR/deploy_$(date +"%Y-%m-%d_%H-%M-%S").log

    # Start log
    - /bin/echo "===== Deployment started at $(date) =====" >> $LOGFILE




    # Pull latest changes from GitHub
    - /bin/echo "Pulling latest changes from GitHub..." >> $LOGFILE
    - cd $REPOPATH && /usr/bin/git pull origin main >> $LOGFILE 2>&1

