deployment:
  tasks:
    # Paths
    - export COMPOSER_BIN=/home/quickerf/composer.phar
    - export REPOPATH=/home/quickerf/laravel_suites_repo/quickerfaster.com
    - export DEPLOYPATH=/home/quickerf/laravel_app
    - export LOGDIR=/home/quickerf/deploy_logs
    - mkdir -p $LOGDIR
    - export LOGFILE=$LOGDIR/deploy_$(date +"%Y-%m-%d_%H-%M-%S").log

    # Start log
    - /bin/echo "===== Deployment started at $(date) =====" >> $LOGFILE




    # Pull latest changes from GitHub
    - /bin/echo "Pulling latest changes from GitHub..." >> $LOGFILE
    - cd $REPOPATH && /usr/bin/git pull origin main >> $LOGFILE 2>&1


    # Clean destination folder but preserve .env, .cpanel.yml, storage, bootstrap/cache
    - /bin/echo "Cleaning destination folder..." >> $LOGFILE
    - /bin/sh -c 'for f in $(/bin/ls -A "$DEPLOYPATH"); do
        [ "$f" = ".env" ] || [ "$f" = ".cpanel.yml" ] || [ "$f" = "storage" ] || [ "$f" = "bootstrap/cache" ] || /bin/rm -rf "$DEPLOYPATH/$f";
      done' >> $LOGFILE 2>&1


    # Copy repository files to deployment path
    - /bin/echo "Copying files to deployment path..." >> $LOGFILE
    - /bin/sh -c 'cd "$REPOPATH" && /bin/cp -a $(/bin/ls -A | grep -vE "^(\.git|\.env|\.cpanel\.yml)$") "$DEPLOYPATH"' >> $LOGFILE 2>&1



    # Ensure Laravel storage and cache directories exist and are writable
    - /bin/echo "Ensuring Laravel storage and cache folders exist..." >> $LOGFILE
    - /bin/sh -c '/bin/mkdir -p $DEPLOYPATH/storage/framework/cache/data \
                   $DEPLOYPATH/storage/framework/sessions \
                   $DEPLOYPATH/storage/framework/views \
                   $DEPLOYPATH/bootstrap/cache \
                   $DEPLOYPATH/storage/logs' >> $LOGFILE 2>&1



